import { describe, expect, it } from "vitest";

import { generatePhpFiles } from "../src/generator.js";

describe("generatePhpFiles", () => {
  it.each([
    "",
    " Skir",
    "Skir ",
    "Skir\n",
    "Skir/Contracts",
    "\\Skir",
    "Skir\\",
    "Skir\\\\Contracts",
    "9Skir",
    "Skir\\invalid-segment",
  ])("rejects malformed PHP namespace %j", (namespace) => {
    expect(() => generatePhpFiles({
      config: { namespace },
      modules: [
        {
          path: "health.skir",
          records: [
            {
              kind: "struct",
              name: "HealthRequest",
              fields: [],
            },
          ],
        },
      ],
    })).toThrow(/canonical PHP namespace/i);
  });

  it("preserves a valid explicit multi-segment PHP namespace", () => {
    const files = generatePhpFiles({
      config: { namespace: "Company\\Contracts" },
      modules: [
        {
          path: "health/health.skir",
          records: [
            {
              kind: "struct",
              name: "HealthRequest",
              fields: [],
            },
          ],
        },
      ],
    });

    expect(files[0]?.code).toContain("namespace Company\\Contracts\\Health;");
  });

  it("uses the Skir root namespace and marks every generated artifact as overwritten", () => {
    const files = generatePhpFiles({
      modules: [
        {
          path: "health/health.skir",
          records: [
            {
              kind: "struct",
              name: "HealthRequest",
              fields: [],
            },
            {
              recordType: "enum",
              name: "HealthStatus",
              fields: [
                { kind: "field", name: "healthy", number: 0 },
              ],
            },
          ],
          methods: [
            {
              kind: "method",
              name: "CheckHealth",
              number: 1,
              requestType: { kind: "record", name: "HealthRequest" },
              responseType: { kind: "record", name: "HealthStatus", recordType: "enum" },
            },
          ],
        },
      ],
    });
    const banner = [
      "/**",
      " * +------------------------------------------------------------+",
      " * |                        DO NOT EDIT                         |",
      " * |      Generated by Skir. Changes will be overwritten.       |",
      " * +------------------------------------------------------------+",
      " */",
    ].join("\n");

    expect(files.find((file) => file.path === "Health/HealthRequest.php")?.code)
      .toContain("namespace Skir\\Health;");
    expect(files).toHaveLength(9);

    for (const file of files.filter((file) => file.path.endsWith(".php"))) {
      expect(file.code).toContain(`declare(strict_types=1);\n\n${banner}\n\nnamespace Skir\\Health;`);
      expect(file.code.match(/DO NOT EDIT/g)).toHaveLength(1);
    }
  });

  it("generates a PHP readonly class for a Skir struct", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "user.skir",
          records: [
            {
              kind: "struct",
              name: "User",
              fields: [
                { kind: "field", name: "user_id", number: 0, type: { kind: "int32" } },
                { kind: "removed", number: 1 },
                { kind: "field", name: "name", number: 2, type: { kind: "string" } },
              ],
            },
          ],
        },
      ],
    });

    expect(files).toHaveLength(2);
    expect(files[0]?.path).toBe("User.php");
    expect(files[0]?.code).toContain("namespace App\\Skir;");
    expect(files[0]?.code).toContain("final readonly class User");
    expect(files[0]?.code).toContain("public int $userId");
    expect(files[0]?.code).toContain("public string $name");
    expect(files[0]?.code).toContain("Field::removed(1)");
    expect(files[0]?.code).toContain("DenseJson::toJson(self::skirType(), $this->toArray())");
  });

  it("generates instantiable PHP classes for empty Skir structs", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "health.skir",
          records: [
            {
              kind: "struct",
              name: "HealthCheckRequest",
              fields: [],
            },
          ],
        },
      ],
    });

    expect(files[0]?.code).toContain("final readonly class HealthCheckRequest");
    expect(files[0]?.code).not.toContain("__construct");
  });

  it("generates a PHP readonly class for a Skir enum", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "subscription-status.skir",
          records: [
            {
              recordType: "enum",
              name: "SubscriptionStatus",
              fields: [
                { kind: "field", name: "free", number: 1 },
                { kind: "field", name: "premium_since", number: 2, type: { kind: "timestamp" } },
              ],
              removedNumbers: [3],
            },
          ],
        },
      ],
    });

    expect(files).toHaveLength(2);
    expect(files[0]?.path).toBe("SubscriptionStatus.php");
    expect(files[0]?.code).toContain("final readonly class SubscriptionStatus");
    expect(files[0]?.code).toContain("public static function free(): self");
    expect(files[0]?.code).toContain("public static function premiumSince(int $value): self");
    expect(files[0]?.code).toContain("Variant::constant('free', 1)");
    expect(files[0]?.code).toContain("Variant::wrapper('premium_since', 2, Type::timestamp())");
    expect(files[0]?.code).toContain("EnumValue::wrapper('premium_since', $value)");
    expect(files[0]?.code).toContain("public function toSkirValue(): EnumValue");
    expect(files[0]?.code).toContain("public static function fromSkirValue(EnumValue $value): SubscriptionStatus");
    expect(files[0]?.code).toContain("public function toDenseValue(): int|array");
    expect(files[0]?.code).toContain("public static function fromDenseValue(int|array $value): SubscriptionStatus");
  });

  it("generates PHP method descriptors for SkirRPC methods", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "users.skir",
          records: [
            {
              kind: "struct",
              name: "GetUserRequest",
              fields: [
                { kind: "field", name: "user_id", number: 0, type: { kind: "int32" } },
              ],
            },
            {
              kind: "struct",
              name: "User",
              fields: [
                { kind: "field", name: "name", number: 0, type: { kind: "string" } },
              ],
            },
          ],
          methods: [
            {
              kind: "method",
              name: "GetUser",
              number: 3180856469,
              requestType: { kind: "record", name: "GetUserRequest" },
              responseType: { kind: "record", name: "User" },
            },
          ],
        },
      ],
    });

    const methodFile = files.find((file) => file.path === "SkirMethods.php");

    expect(methodFile?.code).toContain("use Skir\\Runtime\\MethodDescriptor;");
    expect(methodFile?.code).toContain("public static function getUser(): MethodDescriptor");
    expect(methodFile?.code).toContain("name: 'GetUser'");
    expect(methodFile?.code).toContain("number: 3180856469");
    expect(methodFile?.code).toContain("requestType: GetUserRequest::skirType()");
    expect(methodFile?.code).toContain("responseType: User::skirType()");
  });

  it("generates the standard PHP server manifest", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "Skir",
      },
      modules: [
        {
          path: "admin/users.skir",
          records: [
            {
              kind: "struct",
              name: "GetUserRequest",
              fields: [],
            },
            {
              kind: "struct",
              name: "GetUserResponse",
              fields: [],
            },
            {
              recordType: "enum",
              name: "UserScope",
              fields: [{ kind: "field", name: "all", number: 0 }],
            },
          ],
          methods: [
            {
              kind: "method",
              name: "GetUser",
              number: 1,
              requestType: { kind: "record", name: "GetUserRequest" },
              responseType: { kind: "record", name: "GetUserResponse" },
            },
            {
              kind: "method",
              name: "FindUsers",
              number: 3,
              requestType: {
                kind: "optional",
                other: { kind: "record", name: "UserScope", recordType: "enum" },
              },
              responseType: { kind: "record", name: "UserScope", recordType: "enum" },
            },
          ],
        },
        {
          path: "health.skir",
          methods: [
            {
              kind: "method",
              name: "CheckHealth",
              number: 2,
              requestType: { kind: "string" },
              responseType: {
                kind: "optional",
                other: { kind: "int64" },
              },
            },
          ],
        },
      ],
    });
    const manifestFile = files.find((file) => file.path === "skir-server-manifest.json");

    expect(manifestFile).toBeDefined();
    expect(JSON.parse(manifestFile?.code ?? "")).toEqual({
      version: 1,
      generator: "skir-php-generator",
      modules: [
        {
          name: "Admin",
          methodEnum: "Skir\\Admin\\AdminSkirMethod",
          methods: [
            {
              name: "GetUser",
              enumCase: "GetUser",
              phpMethod: "getUser",
              requestType: "Skir\\Admin\\GetUserRequest",
              requestClass: "Skir\\Admin\\GetUserRequest",
              responseType: "Skir\\Admin\\GetUserResponse",
              responseClass: "Skir\\Admin\\GetUserResponse",
            },
            {
              name: "FindUsers",
              enumCase: "FindUsers",
              phpMethod: "findUsers",
              requestType: "?Skir\\Admin\\UserScope",
              requestClass: null,
              responseType: "Skir\\Admin\\UserScope",
              responseClass: "Skir\\Admin\\UserScope",
            },
          ],
        },
        {
          name: "_Root",
          methodEnum: "Skir\\SkirMethod",
          methods: [
            {
              name: "CheckHealth",
              enumCase: "CheckHealth",
              phpMethod: "checkHealth",
              requestType: "string",
              requestClass: null,
              responseType: "int|string|null",
              responseClass: null,
            },
          ],
        },
      ],
    });
    expect(manifestFile?.code.endsWith("\n")).toBe(true);
    expect(files.at(-1)?.path).toBe("skir-server-manifest.json");
  });

  it("uses normalized PHP namespace segments for manifest module identities", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "Skir",
      },
      modules: [
        {
          path: "user-profile/profile.skir",
          records: [
            { kind: "struct", name: "ProfileRequest", fields: [] },
            { kind: "struct", name: "ProfileResponse", fields: [] },
          ],
          methods: [
            {
              kind: "method",
              name: "GetProfile",
              number: 1,
              requestType: { kind: "record", name: "ProfileRequest" },
              responseType: { kind: "record", name: "ProfileResponse" },
            },
          ],
        },
        {
          path: "admin/users/users.skir",
          methods: [
            { kind: "method", name: "ListUsers", number: 2 },
          ],
        },
        {
          path: "admin.users/users.skir",
          methods: [
            { kind: "method", name: "ListAdmins", number: 3 },
          ],
        },
        {
          path: "health.skir",
          methods: [
            { kind: "method", name: "Health", number: 4 },
          ],
        },
        {
          path: "Root/root.skir",
          methods: [
            { kind: "method", name: "DirectoryRoot", number: 5 },
          ],
        },
      ],
    });
    const manifestFile = files.find((file) => file.path === "skir-server-manifest.json");
    const manifest = JSON.parse(manifestFile?.code ?? "");

    expect(manifest.modules.map((module: { name: string }) => module.name)).toEqual([
      "UserProfile",
      "Admin.Users",
      "AdminUsers",
      "_Root",
      "Root",
    ]);
    expect(manifest.modules.flatMap((module: { name: string; methods: { name: string }[] }) =>
      module.methods.map((method) => `${module.name}.${method.name}`))).toEqual([
      "UserProfile.GetProfile",
      "Admin.Users.ListUsers",
      "AdminUsers.ListAdmins",
      "_Root.Health",
      "Root.DirectoryRoot",
    ]);
    expect(manifest.modules[0]).toMatchObject({
      methodEnum: "Skir\\UserProfile\\UserProfileSkirMethod",
      methods: [
        {
          requestType: "Skir\\UserProfile\\ProfileRequest",
          requestClass: "Skir\\UserProfile\\ProfileRequest",
          responseType: "Skir\\UserProfile\\ProfileResponse",
          responseClass: "Skir\\UserProfile\\ProfileResponse",
        },
      ],
    });
    expect(manifest.modules[1]).toMatchObject({
      methodEnum: "Skir\\Admin\\Users\\AdminUsersSkirMethod",
    });
    expect(manifest.modules[2]).toMatchObject({
      methodEnum: "Skir\\AdminUsers\\AdminUsersSkirMethod",
    });
    expect(manifest.modules[3]).toMatchObject({
      methodEnum: "Skir\\SkirMethod",
    });
    expect(manifest.modules[4]).toMatchObject({
      methodEnum: "Skir\\Root\\RootSkirMethod",
    });
  });

  it("rejects distinct source directories that normalize to the same module identity", () => {
    expect(() => generatePhpFiles({
      modules: [
        {
          path: "user-profile/profile.skir",
          methods: [
            { kind: "method", name: "GetProfile", number: 1 },
          ],
        },
        {
          path: "user_profile/account.skir",
          methods: [
            { kind: "method", name: "GetAccount", number: 2 },
          ],
        },
      ],
    })).toThrow(/UserProfile.*user-profile.*user_profile/i);
  });

  it("reserves the leading underscore module identity for root-level methods", () => {
    const files = generatePhpFiles({
      modules: [
        {
          path: "_root/profile.skir",
          methods: [
            { kind: "method", name: "GetProfile", number: 1 },
          ],
        },
      ],
    });
    const manifestFile = files.find((file) => file.path === "skir-server-manifest.json");
    const manifest = JSON.parse(manifestFile?.code ?? "");

    expect(manifest.modules[0]?.name).toBe("Root");
    expect(manifest.modules[0]?.name).not.toBe("_Root");
  });

  it("uses record locations for cross-module, nested, and optional manifest types", () => {
    const addressRecord = {
      kind: "record",
      key: "common/address.skir:0",
      recordType: "struct" as const,
      name: "Address",
      fields: [],
    };
    const envelopeRecord = {
      kind: "record",
      key: "admin/envelope.skir:0",
      recordType: "struct" as const,
      name: "Envelope",
      fields: [],
    };
    const metadataRecord = {
      kind: "record",
      key: "admin/envelope.skir:1",
      recordType: "struct" as const,
      name: "Metadata",
      fields: [],
    };
    const scopeRecord = {
      kind: "record",
      key: "common/scope.skir:0",
      recordType: "enum" as const,
      name: "Scope",
      fields: [],
    };
    const files = generatePhpFiles({
      config: {
        namespace: "Skir",
      },
      recordMap: new Map([
        [
          addressRecord.key,
          {
            kind: "record-location",
            record: addressRecord,
            recordAncestors: [addressRecord],
            modulePath: "common/address.skir",
          },
        ],
        [
          metadataRecord.key,
          {
            kind: "record-location",
            record: metadataRecord,
            recordAncestors: [envelopeRecord, metadataRecord],
            modulePath: "admin/envelope.skir",
          },
        ],
        [
          scopeRecord.key,
          {
            kind: "record-location",
            record: scopeRecord,
            recordAncestors: [scopeRecord],
            modulePath: "common/scope.skir",
          },
        ],
      ]),
      modules: [
        {
          path: "admin/service.skir",
          methods: [
            {
              kind: "method",
              name: "ResolveAddress",
              number: 1,
              requestType: {
                kind: "record",
                key: addressRecord.key,
                nameParts: [{ token: { text: "Address" } }],
              },
              responseType: {
                kind: "record",
                key: metadataRecord.key,
                nameParts: [
                  { token: { text: "Envelope" } },
                  { token: { text: "Metadata" } },
                ],
              },
            },
            {
              kind: "method",
              name: "MaybeResolveAddress",
              number: 2,
              requestType: {
                kind: "optional",
                other: {
                  kind: "record",
                  key: addressRecord.key,
                  nameParts: [{ token: { text: "Address" } }],
                },
              },
              responseType: { kind: "bool" },
            },
            {
              kind: "method",
              name: "FindByScope",
              number: 3,
              requestType: {
                kind: "record",
                key: scopeRecord.key,
                nameParts: [{ token: { text: "Scope" } }],
              },
              responseType: { kind: "bool" },
            },
          ],
        },
      ],
    });
    const manifestFile = files.find((file) => file.path === "skir-server-manifest.json");

    expect(JSON.parse(manifestFile?.code ?? "")).toEqual({
      version: 1,
      generator: "skir-php-generator",
      modules: [
        {
          name: "Admin",
          methodEnum: "Skir\\Admin\\AdminSkirMethod",
          methods: [
            {
              name: "ResolveAddress",
              enumCase: "ResolveAddress",
              phpMethod: "resolveAddress",
              requestType: "Skir\\Common\\Address",
              requestClass: "Skir\\Common\\Address",
              responseType: "Skir\\Admin\\EnvelopeMetadata",
              responseClass: "Skir\\Admin\\EnvelopeMetadata",
            },
            {
              name: "MaybeResolveAddress",
              enumCase: "MaybeResolveAddress",
              phpMethod: "maybeResolveAddress",
              requestType: "?Skir\\Common\\Address",
              requestClass: "Skir\\Common\\Address",
              responseType: "bool",
              responseClass: null,
            },
            {
              name: "FindByScope",
              enumCase: "FindByScope",
              phpMethod: "findByScope",
              requestType: "Skir\\Common\\Scope",
              requestClass: null,
              responseType: "bool",
              responseClass: null,
            },
          ],
        },
      ],
    });
  });

  it("generates a typed SkirRPC client for SkirRPC methods", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "users.skir",
          records: [
            {
              kind: "struct",
              name: "GetUserRequest",
              fields: [
                { kind: "field", name: "user_id", number: 0, type: { kind: "int32" } },
              ],
            },
            {
              kind: "struct",
              name: "User",
              fields: [
                { kind: "field", name: "name", number: 0, type: { kind: "string" } },
              ],
            },
          ],
          methods: [
            {
              kind: "method",
              name: "GetUser",
              number: 3180856469,
              requestType: { kind: "record", name: "GetUserRequest" },
              responseType: { kind: "record", name: "User" },
            },
          ],
        },
      ],
    });

    const clientFile = files.find((file) => file.path === "SkirRpcClient.php");

    expect(clientFile?.code).toContain("use Skir\\Client\\SkirClient;");
    expect(clientFile?.code).toContain("final readonly class SkirRpcClient");
    expect(clientFile?.code).toContain("public function __construct(");
    expect(clientFile?.code).toContain("private SkirClient $client,");
    expect(clientFile?.code).toContain("public function getUser(GetUserRequest $request): User");
    expect(clientFile?.code).toContain("$response = $this->client->invoke(SkirMethods::getUser(), $request->toArray());");
    expect(clientFile?.code).toContain("return User::fromArray($response);");
  });

  it("generates typed server procedure contracts for SkirRPC methods", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "users.skir",
          records: [
            {
              kind: "struct",
              name: "GetUserRequest",
              fields: [
                { kind: "field", name: "user_id", number: 0, type: { kind: "int32" } },
              ],
            },
            {
              kind: "struct",
              name: "User",
              fields: [
                { kind: "field", name: "name", number: 0, type: { kind: "string" } },
              ],
            },
          ],
          methods: [
            {
              kind: "method",
              name: "GetUser",
              number: 3180856469,
              requestType: { kind: "record", name: "GetUserRequest" },
              responseType: { kind: "record", name: "User" },
            },
          ],
        },
      ],
    });

    const proceduresFile = files.find((file) => file.path === "SkirProcedures.php");
    const providerFile = files.find((file) => file.path === "SkirProcedureProvider.php");
    const abstractProceduresFile = files.find((file) => file.path === "AbstractSkirProcedures.php");
    const methodEnumFile = files.find((file) => file.path === "SkirMethod.php");

    expect(methodEnumFile?.code).toContain("enum SkirMethod implements SkirMethodReference");
    expect(methodEnumFile?.code).toContain("case GetUser;");
    expect(methodEnumFile?.code).toContain("self::GetUser => SkirMethods::getUser(),");
    expect(proceduresFile?.code).toContain("interface SkirProcedures");
    expect(proceduresFile?.code).toContain("public function getUser(GetUserRequest $request, SkirContext $context): User;");
    expect(providerFile?.code).toContain("use Skir\\Server\\ProcedureProvider;");
    expect(providerFile?.code).toContain("final readonly class SkirProcedureProvider implements ProcedureProvider");
    expect(providerFile?.code).toContain("private SkirProcedures $procedures,");
    expect(providerFile?.code).toContain("$server->addMethod(SkirMethods::getUser(), function (mixed $request, SkirContext $context): mixed {");
    expect(providerFile?.code).toContain("$response = $this->procedures->getUser(GetUserRequest::fromArray($request), $context);");
    expect(providerFile?.code).toContain("return $response->toArray();");
    expect(abstractProceduresFile?.code).toContain("abstract class AbstractSkirProcedures implements ProcedureProvider");
    expect(abstractProceduresFile?.code).toContain("abstract public function getUser(GetUserRequest $request, SkirContext $context): User;");
    expect(abstractProceduresFile?.code).toContain("$server->addMethod(SkirMethods::getUser(), function (mixed $request, SkirContext $context): mixed {");
    expect(abstractProceduresFile?.code).toContain("$response = $this->getUser(GetUserRequest::fromArray($request), $context);");
    expect(abstractProceduresFile?.code).toContain("return $response->toArray();");
  });

  it("uses module directories as PHP subnamespaces and output directories", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "admin/users.skir",
          records: [
            {
              kind: "struct",
              name: "GetUserRequest",
              fields: [
                { kind: "field", name: "user_id", number: 0, type: { kind: "int32" } },
              ],
            },
            {
              kind: "struct",
              name: "User",
              fields: [
                { kind: "field", name: "name", number: 0, type: { kind: "string" } },
              ],
            },
          ],
          methods: [
            {
              kind: "method",
              name: "GetUser",
              number: 3180856469,
              requestType: { kind: "record", name: "GetUserRequest" },
              responseType: { kind: "record", name: "User" },
            },
          ],
        },
      ],
    });

    const userFile = files.find((file) => file.path === "Admin/User.php");
    const requestFile = files.find((file) => file.path === "Admin/GetUserRequest.php");
    const methodsFile = files.find((file) => file.path === "Admin/SkirMethods.php");
    const clientFile = files.find((file) => file.path === "Admin/SkirRpcClient.php");
    const proceduresFile = files.find((file) => file.path === "Admin/SkirProcedures.php");
    const providerFile = files.find((file) => file.path === "Admin/SkirProcedureProvider.php");
    const abstractProceduresFile = files.find((file) => file.path === "Admin/AbstractSkirProcedures.php");
    const methodEnumFile = files.find((file) => file.path === "Admin/AdminSkirMethod.php");

    expect(userFile?.code).toContain("namespace App\\Skir\\Admin;");
    expect(requestFile?.code).toContain("namespace App\\Skir\\Admin;");
    expect(methodsFile?.code).toContain("namespace App\\Skir\\Admin;");
    expect(clientFile?.code).toContain("namespace App\\Skir\\Admin;");
    expect(proceduresFile?.code).toContain("namespace App\\Skir\\Admin;");
    expect(providerFile?.code).toContain("namespace App\\Skir\\Admin;");
    expect(abstractProceduresFile?.code).toContain("namespace App\\Skir\\Admin;");
    expect(methodEnumFile?.code).toContain("namespace App\\Skir\\Admin;");
    expect(methodEnumFile?.code).toContain("enum AdminSkirMethod implements SkirMethodReference");
    expect(methodsFile?.code).toContain("requestType: GetUserRequest::skirType()");
    expect(methodsFile?.code).toContain("responseType: User::skirType()");
    expect(clientFile?.code).toContain("public function getUser(GetUserRequest $request): User");
  });

  it("qualifies record references from other module namespaces", () => {
    const addressRecord = {
      kind: "record",
      recordType: "struct" as const,
      name: "Address",
      fields: [
        { kind: "field" as const, name: "city", number: 0, type: { kind: "primitive", primitive: "string" } },
      ],
    };

    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      recordMap: new Map([
        [
          "common/address.skir:0",
          {
            kind: "record-location",
            record: addressRecord,
            recordAncestors: [addressRecord],
            modulePath: "common/address.skir",
          },
        ],
      ]),
      modules: [
        {
          path: "admin/users.skir",
          records: [
            {
              kind: "struct",
              name: "User",
              fields: [
                {
                  kind: "field",
                  name: "address",
                  number: 0,
                  type: {
                    kind: "record",
                    key: "common/address.skir:0",
                    nameParts: [{ token: { text: "Address" } }],
                  },
                },
              ],
            },
          ],
        },
      ],
    });

    const userFile = files.find((file) => file.path === "Admin/User.php");

    expect(userFile?.code).toContain("use App\\Skir\\Common\\Address;");
    expect(userFile?.code).toContain("public Address $address");
    expect(userFile?.code).toContain("Field::value('address', 0, Address::skirType())");
    expect(userFile?.code).toContain("address: Address::fromArray($data['address'])");
    expect(userFile?.code).not.toContain("\\App\\Skir\\Common\\Address");
  });

  it("keeps fully qualified record references when an import would collide", () => {
    const addressRecord = {
      kind: "record",
      recordType: "struct" as const,
      name: "Address",
      fields: [
        { kind: "field" as const, name: "city", number: 0, type: { kind: "primitive", primitive: "string" } },
      ],
    };

    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      recordMap: new Map([
        [
          "common/address.skir:0",
          {
            kind: "record-location",
            record: addressRecord,
            recordAncestors: [addressRecord],
            modulePath: "common/address.skir",
          },
        ],
      ]),
      modules: [
        {
          path: "admin/address.skir",
          records: [
            {
              kind: "struct",
              name: "Address",
              fields: [
                {
                  kind: "field",
                  name: "billing_address",
                  number: 0,
                  type: {
                    kind: "record",
                    key: "common/address.skir:0",
                    nameParts: [{ token: { text: "Address" } }],
                  },
                },
              ],
            },
          ],
        },
      ],
    });

    const addressFile = files.find((file) => file.path === "Admin/Address.php");

    expect(addressFile?.code).not.toContain("use App\\Skir\\Common\\Address;");
    expect(addressFile?.code).toContain("public \\App\\Skir\\Common\\Address $billingAddress");
    expect(addressFile?.code).toContain("Field::value('billing_address', 0, \\App\\Skir\\Common\\Address::skirType())");
  });

  it("disambiguates duplicate class names in the same PHP namespace", () => {
    const usersUserRecord = {
      kind: "record",
      key: "admin/users.skir:0",
      recordType: "struct" as const,
      name: "User",
      fields: [
        { kind: "field" as const, name: "email", number: 0, type: { kind: "primitive", primitive: "string" } },
      ],
    };

    const profilesUserRecord = {
      kind: "record",
      key: "admin/profiles.skir:0",
      recordType: "struct" as const,
      name: "User",
      fields: [
        { kind: "field" as const, name: "display_name", number: 0, type: { kind: "primitive", primitive: "string" } },
      ],
    };

    const auditRecord = {
      kind: "record",
      key: "admin/audits.skir:0",
      recordType: "struct" as const,
      name: "Audit",
      fields: [
        {
          kind: "field" as const,
          name: "actor",
          number: 0,
          type: {
            kind: "record",
            key: "admin/users.skir:0",
            nameParts: [{ token: { text: "User" } }],
          },
        },
      ],
    };

    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      recordMap: new Map([
        [
          "admin/users.skir:0",
          {
            kind: "record-location",
            record: usersUserRecord,
            recordAncestors: [usersUserRecord],
            modulePath: "admin/users.skir",
          },
        ],
        [
          "admin/profiles.skir:0",
          {
            kind: "record-location",
            record: profilesUserRecord,
            recordAncestors: [profilesUserRecord],
            modulePath: "admin/profiles.skir",
          },
        ],
        [
          "admin/audits.skir:0",
          {
            kind: "record-location",
            record: auditRecord,
            recordAncestors: [auditRecord],
            modulePath: "admin/audits.skir",
          },
        ],
      ]),
      modules: [
        {
          path: "admin/users.skir",
          records: [
            {
              kind: "record-location",
              record: usersUserRecord,
              recordAncestors: [usersUserRecord],
              modulePath: "admin/users.skir",
            },
          ],
        },
        {
          path: "admin/profiles.skir",
          records: [
            {
              kind: "record-location",
              record: profilesUserRecord,
              recordAncestors: [profilesUserRecord],
              modulePath: "admin/profiles.skir",
            },
          ],
        },
        {
          path: "admin/audits.skir",
          records: [
            {
              kind: "record-location",
              record: auditRecord,
              recordAncestors: [auditRecord],
              modulePath: "admin/audits.skir",
            },
          ],
        },
      ],
    });

    const usersUserFile = files.find((file) => file.path === "Admin/UsersUser.php");
    const profilesUserFile = files.find((file) => file.path === "Admin/ProfilesUser.php");
    const auditFile = files.find((file) => file.path === "Admin/Audit.php");

    expect(files.map((file) => file.path)).not.toContain("Admin/User.php");
    expect(usersUserFile?.code).toContain("final readonly class UsersUser");
    expect(profilesUserFile?.code).toContain("final readonly class ProfilesUser");
    expect(auditFile?.code).toContain("public UsersUser $actor");
    expect(auditFile?.code).toContain("Field::value('actor', 0, UsersUser::skirType())");
  });

  it("types and normalizes generated record fields", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "user.skir",
          records: [
            {
              kind: "struct",
              name: "Address",
              fields: [
                { kind: "field", name: "city", number: 0, type: { kind: "string" } },
              ],
            },
            {
              kind: "struct",
              name: "User",
              fields: [
                { kind: "field", name: "address", number: 0, type: { kind: "record", name: "Address" } },
              ],
            },
          ],
        },
      ],
    });

    const userFile = files.find((file) => file.path === "User.php");

    expect(userFile?.code).toContain("public Address $address");
    expect(userFile?.code).toContain("'address' => $this->address->toArray()");
    expect(userFile?.code).toContain("address: Address::fromArray($data['address'])");
  });

  it("normalizes generated enum fields through Skir runtime values", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "user.skir",
          records: [
            {
              recordType: "enum",
              name: "SubscriptionStatus",
              fields: [
                { kind: "field", name: "free", number: 1 },
              ],
            },
            {
              kind: "struct",
              name: "User",
              fields: [
                { kind: "field", name: "subscription_status", number: 0, type: { kind: "record", name: "SubscriptionStatus", recordType: "enum" } },
              ],
            },
          ],
        },
      ],
    });

    const userFile = files.find((file) => file.path === "User.php");

    expect(userFile?.code).toContain("'subscription_status' => $this->subscriptionStatus->toSkirValue()");
    expect(userFile?.code).toContain("subscriptionStatus: SubscriptionStatus::fromSkirValue($data['subscription_status'])");
    expect(userFile?.code).not.toContain("$this->subscriptionStatus->toArray()");
    expect(userFile?.code).not.toContain("SubscriptionStatus::fromArray($data['subscription_status'])");
  });

  it("normalizes optional generated enum fields through Skir runtime values", () => {
    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "user.skir",
          records: [
            {
              recordType: "enum",
              name: "SubscriptionStatus",
              fields: [
                { kind: "field", name: "free", number: 1 },
              ],
            },
            {
              kind: "struct",
              name: "User",
              fields: [
                {
                  kind: "field",
                  name: "subscription_status",
                  number: 0,
                  type: {
                    kind: "optional",
                    other: {
                      kind: "record",
                      name: "SubscriptionStatus",
                      recordType: "enum",
                    },
                  },
                },
              ],
            },
          ],
        },
      ],
    });

    const userFile = files.find((file) => file.path === "User.php");

    expect(userFile?.code).toContain("'subscription_status' => $this->subscriptionStatus === null ? null : $this->subscriptionStatus->toSkirValue()");
    expect(userFile?.code).toContain("subscriptionStatus: $data['subscription_status'] === null ? null : SubscriptionStatus::fromSkirValue($data['subscription_status'])");
    expect(userFile?.code).not.toContain("$this->subscriptionStatus->toArray()");
    expect(userFile?.code).not.toContain("SubscriptionStatus::fromArray($data['subscription_status'])");
  });

  it("flattens nested Skir record locations into stable PHP class names", () => {
    const envelopeRecord = {
      kind: "record",
      recordType: "struct" as const,
      name: "Envelope",
      fields: [
        {
          kind: "field" as const,
          name: "metadata",
          number: 0,
          type: {
            kind: "record",
            nameParts: [
              { token: { text: "Envelope" } },
              { token: { text: "Metadata" } },
            ],
          },
        },
      ],
    };

    const metadataRecord = {
      kind: "record",
      recordType: "struct" as const,
      name: "Metadata",
      fields: [
        { kind: "field" as const, name: "trace_id", number: 0, type: { kind: "string" } },
      ],
    };

    const files = generatePhpFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [
        {
          path: "envelope.skir",
          records: [
            {
              kind: "record-location",
              record: metadataRecord,
              recordAncestors: [envelopeRecord, metadataRecord],
            },
            {
              kind: "record-location",
              record: envelopeRecord,
              recordAncestors: [envelopeRecord],
            },
          ],
        },
      ],
    });

    const envelopeFile = files.find((file) => file.path === "Envelope.php");
    const metadataFile = files.find((file) => file.path === "EnvelopeMetadata.php");

    expect(metadataFile?.code).toContain("final readonly class EnvelopeMetadata");
    expect(envelopeFile?.code).toContain("public EnvelopeMetadata $metadata");
    expect(envelopeFile?.code).toContain("Field::value('metadata', 0, EnvelopeMetadata::skirType())");
    expect(envelopeFile?.code).toContain("metadata: EnvelopeMetadata::fromArray($data['metadata'])");
  });
});
